= LucidJ Architecture Reference
:page-layout: book

== OSGi

OSGi is the de-facto (yet mostly unknown) standard for Java modularization. Long before Jigsaw was even drafted, OSGi was running below the surface of many systems, like Eclipse. Even thou the achievements of Jigsaw still belongs to the future, it already contributed a great deal by making modularization into the news. That's a good thing, and a gift to anyone who cares about software architecture.
// It would be good to have a timeline of adoption for OSGi X timeline of Jigsaw

== The Problems to Solve

The nature of OSGi and our goals leads to some unusual problems to research and solve. At first they may seem a burden from OSGi usage, but actually they arise from the needs (and challenges) of modularization. Modularization is the real tough challenge.

=== Problem #1 - The Classpath Hell

TODO::
* Export the very minimum needed classes/interfaces;
* The private classpath (Include-Resource, Bundle-ClassPath directives).

=== Problem #2 - Use Services and Interfaces Instead of Classes

TODO::
* The title looks like a solution, but it's a unusual way to code;
* Direct class (implementation) dependencies are bad because the jar bundle becomes hardwired;
* We need jar bundles with interfaces apart from implementation bundles;
* We need simple enough service discovery mechanics.

=== Problem #3 - The Zoombie Objects

TODO::
* Zombie objects are objects created by a bundle but active after the bundle is gone;
* We need to keep track of them, but it's hard because we don't have mechanisms to notify pojos from it's parent bundle death;
* They move slowly but can create big havoc :)

=== Problem #4 - ClassLoader Acrobatics

TODO::
* ClassLoader tweaking is bad for your health and sleep;
* Way too many libraries/softwares use ClassLoader acrobacies to work;
* Many ClassLoader problems are solved with great elegance with OSGi;
* Treat ClassLoader as no man's land and leave it to whoever wants to fight for.

=== Problem #5 - Interfaces are not the Only Answer: Aggregates

TODO::
* Describe

=== Problem #6 - Distributed OSGi

TODO::
* Describe
* The Elephant in the Room
