= LucidJ Architecture Reference
:page-layout: book

== OSGi

OSGi is the de-facto (yet mostly unknown) standard for Java modularization. Long before Jigsaw was even drafted, OSGi was running below the surface of many systems, like Eclipse. Even thou the achievements of Jigsaw still belongs to the future, it already contributed a great deal by making modularization into the news. That's a good thing, and a gift to anyone who cares about software architecture.
// It would be good to have a timeline of adoption for OSGi X timeline of Jigsaw

== The Problems to Solve

The nature of OSGi and our goals leads to some unusual problems to research and solve. At first they may seem a burden from OSGi usage, but actually they arise from the needs (and challenges) of modularization. Modularization is the real tough challenge.

=== Problem #1 - The Classpath Hell

TODO::
* Export the very minimum needed classes/interfaces;
* The private classpath (Include-Resource, Bundle-ClassPath directives).

=== Problem #2 - Use Services and Interfaces Instead of Classes

TODO::
* The title looks like a solution, but it's a unusual way to code;
* Direct class (implementation) dependencies are bad because the jar bundle becomes hardwired;
* We need jar bundles with interfaces apart from implementation bundles;
* We need simple enough service discovery mechanics.

==== From Modules to Services (and µServices)

Modules are great for µservices;
µservices are the real strength of OSGi;

=== Problem #3 - The Zoombie Objects

TODO::
* Zombie objects are objects created by a bundle but active after the bundle is gone;
* We need to keep track of them, but it's hard because we don't have mechanisms to notify pojos from it's parent bundle death;
* They move slowly but can create big havoc :)

The OSGi javadoc calls zombies any Bundle in the Bundle.UNINSTALLED state. It's the bundle's final state. In fact, it can only be reached through stale references. That's why they are aptly called _Zombie Bundles_.

However zombie bundles are not alone. The bundle may have created many objects, and their references may be hanging over the system. These stale objects, bound to defunct bundles, are called _Zombie Objects_.

How to detect zombie objects?
Method 1: Invalid bundle from classloader

==== Service Objects

The _Service Objects_ are handled in two special ways:

* They receive _Validate_ and _Invalidate_ messages marking its lifecycle;
* They are stored on a _WeakReference_ pool. As long as their WeakReferences are valid, we can assume they have references hanging around. This allows to track stale objects leaking from their source bundle.

==== Service Handles

The _Service Handles_ are used to hide the relevant objects inside the bundle. Instead of the object, the only thing known outside is an Integer number, called _Service Handle_. For those who are familiar with C, it's essentially the same as the file descriptors from the low level API, like _open()_, _creat()_ and _close()_. Since the object references never travels outside the bundle, both it's lifecycle and references can be closely tracked.
// TODO: Take open() example into a proper place

=== Problem #4 - ClassLoader Acrobatics

TODO::
* ClassLoader tweaking is bad for your health and sleep;
* Way too many libraries/softwares use ClassLoader acrobacies to work;
* Many ClassLoader problems are solved with great elegance with OSGi;
* Treat ClassLoader as no man's land and leave it to whoever wants to fight for.

=== Problem #5 - Interfaces are not the Only Answer: Aggregates

TODO::
* Describe

=== Problem #6 - Distributed OSGi

TODO::
* Describe
* The Elephant in the Room
