= LucidJ Reference Guide
:page-layout: book

== Overview

LucidJ is inspired by 80's personal computers: turn on, code and run.

== Components

OSGi is the de-facto (yet mostly unknown) standard for Java modularization. Long before Jigsaw was even drafted, OSGi was running below the surface of many systems, like Eclipse. Even thou the achievements of Jigsaw still belongs to the future, it already contributed a great deal by making modularization into the news. That's a good thing, and a gift to anyone who cares about software architecture.
// It would be good to have a timeline of adoption for OSGi X timeline of Jigsaw

=== Apache Karaf

Life in java was easy. Grab the JARs you need to build your classpath and you're good to go. Things started to get complicated when we started, very soon, to deal with versioning and the dark science of combining often compatible JARs into a meaningful classpath. -> jar hell

=== Vaadin

In a nutshell, OSGi transforms the familiar JAR files into modularization units. It does it breaking the traditional classpath mechanics. Instead of build a classpath with a lot of JARs, it reverses the logic and every JAR get an individual classloader and a classpath. But, how to they talk each other?
